### ISSUE TITLE
Errors when compiling tvl1flow and Solutions

### ISSUE THREAD

**Issue by selous123** [tehret/blind-denoising#1]
ubuntu 16.04
cmake 3.5.1

1. fatal error: png.h: No such file or directory
```
 sudo apt-get install libpng-dev
```
2. fatal error: jpeglib.h: No such file or directory
```
sudo apt-get install libjpeg-dev
```
3. fatal error: tiffio.h: No such file or directory
```
sudo apt-get install libtiff5-dev
```

**Comment by ShaofengZou** [comment]
So appreciate about that!
I encountered the same trouble right now and thank you for your help.

**Comment by Lucky-H6** [comment]
Really appreciated!

**Comment by Lucky-H6** [comment]
Appreciate!
